name: build github page

on:
  push:
    branches:
      - master

    # Only files changed can trigger this workflow
    paths:
      - '.github/workflows/vite-build.yml' # This workflow file
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - '*.js'
      - '*.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  vite-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: utc-v2.allen0099.tw
