name: build github page

on:
  push:
    branches:
      - master

  # Only files changed can trigger this workflow
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - '*.js'
      - '*.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  vite-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
